version: '3.0'

volumes:
  postgres-data:
  neo4j-data:
  mongo-data-notification:
  mongo-data-reminder:

services:
  # Eldycare backend services
  discovery-service:
    container_name: discovery-service
    image: eldycare/discovery-service:latest
    ports:
      - 8761:8761
    environment:
      - container_discovery=discovery-service
  api-gateway-service:
    container_name: api-gateway-service
    image: eldycare/api-gateway-service:latest
    ports:
      - 8888:8888
    environment:
      - container_discovery=discovery-service
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
  authentication-service:
    container_name: authentication-service
    image: eldycare/authentication-service:latest
    ports:
      - 8080:8080
    depends_on:
      - postgres
      - rabbitmq
    environment:
      - container_discovery=discovery-service
      - POSTGRES_DB=eldycare
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=postgresql
      - POSTGRES_PORT=5432
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
  user-service:
    container_name: user-service
    image: eldycare/user-service:latest
    ports:
      - 8081:8081
    depends_on:
      - neo4j
      - rabbitmq
    environment:
      - container_discovery=discovery-service
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=saga-pablo-lagoon-java-license-4169
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
  notification-service:
    container_name: notification-service
    image: eldycare/notification-service:latest
    ports:
      - 8082:8082
    depends_on:
      - mongodb-notification
      - rabbitmq
    environment:
      - container_discovery=discovery-service
      - MongoDB_USERNAME=mongo
      - MongoDB_PASSWORD=mongo
      - MongoDB_DATABASE=notifications
      - MongoDB_CLUSTER_HOST=mongodb-notification
      - MongoDB_CLUSTER_PORT=27017
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
  reminder-service:
    container_name: reminder-service
    image: eldycare/reminder-service:latest
    ports:
      - 8083:8083
    depends_on:
      - mongodb-reminder
    environment:
      - container_discovery=discovery-service
      - MongoDB_USERNAME=mongo
      - MongoDB_PASSWORD=mongo
      - MongoDB_DATABASE=reminders
      - MongoDB_CLUSTER_HOST=mongodb-reminder
      - MongoDB_CLUSTER_PORT=27018





  # Database services
  postgres:
    container_name: postgresql
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
        - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: eldycare
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  mongodb-notification:
    container_name: mongodb-notification
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongo-data-notification:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
#  mongo-express-notification:
#    container_name: mongo-express-notification
#    image: mongo-express:latest
#    ports:
#      - 9901:8081
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
#      ME_CONFIG_MONGODB_ADMINPASSWORD: mongo
#      ME_CONFIG_MONGODB_SERVER: mongodb-notification

  mongodb-reminder:
    container_name: mongodb-reminder
    image: mongo:latest
    ports:
      - 27018:27017
    volumes:
      - mongo-data-reminder:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
#  mongo-express-reminder:
#    container_name: mongo-express-reminder
#    image: mongo-express:latest
#    ports:
#      - 9902:8081
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
#      ME_CONFIG_MONGODB_ADMINPASSWORD: mongo
#      ME_CONFIG_MONGODB_SERVER: mongodb-reminder

  neo4j:
    container_name: neo4j
    image: neo4j:latest
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - neo4j-data:/data
    environment:
      - NEO4J_AUTH=neo4j/saga-pablo-lagoon-java-license-4169

  # Broker
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.12-management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
